import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Footer from './Footer';

interface Props {
  children: React.ReactNode;
}

const Layout: NextPage<Props> = ({ children }) => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Patrik Staaf - Web Developer Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width' />
        <meta
          name='description'
          content='Patrik Staaf Web Developer Portfolio'
        />

        <meta
          property='og:title'
          content='Patrik Staaf Web Developer Portfolio'
        />
        <meta
          property='og:image'
          content='https://patrikstaaf.com/og-image.webp'
        />
        <meta property='og:image:alt' content='Screenshot of home page' />
        <meta
          property='og:description'
          content='Patrik Staaf Web Developer Portfolio'
        />
        <meta property='og:type' content='website' />

        <meta
          property='twitter:title'
          content='Patrik Staaf Web Developer Portfolio'
        />
        <meta
          property='twitter:image'
          content='https://patrikstaaf.com/og-image.webp'
        />
        <meta property='twitter:image:alt' content='Screenshot of home page' />
        <meta
          property='twitter:description'
          content='Patrik Staaf Web Developer Portfolio'
        />

        <meta name='theme-color' content='#fff' />
        <meta property='og:url' content={router.asPath} />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <div className='mx-auto antialiased max-w-2xl font-inter pt-20 pb-32 w-full'>
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
